### ISSUE TITLE
Create tests for home page

### ISSUE THREAD

**Issue by bjdixon** [mozilla/oneanddone-tests#3]
I'd like to add some tests if that's okay. I can continue adding once bitgeeky's pull has been merged.

**Comment by bobsilverberg** [comment]
@bjdixon I am going to close this issue, but will open one or more other issues with some specific non-destructive tests that I think would be valuable for One and Done. Please feel free to take one of those if you're still interested in helping.

**Comment by bjdixon** [comment]
I'll take a look at the new issues. Thanks =)
