### ISSUE TITLE
Create a test to check the Available Tasks page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/oneanddone-tests#40]
This test should be non-destructive, so it cannot log in to the site. It should do the following:
1. Open the home page.
2. Click the `AVAILABLE TASKS` link in the header.
3. Verify that the browser is on the Available Tasks page.
4. Verify that the list of tasks is visible and that at least one task is listed.
5. Click on the first task in the list.
6. Verify that the browser is on the Task Detail page for that task.

**Comment by skapil** [comment]
@bobsilverberg I am working on this, hoping nobody has taken this ticket yet. 
One thing I don't understand is 3rd step. The step says:  
Verify that the browser is on the Available Tasks page.
But on this page: https://oneanddone.mozilla.org/tasks/available/
I see project name as "Browser" but don't see task as "Browser" however there are some task which contain "Browser" as word but not as task.
Can you please explain on this.

**Comment by bobsilverberg** [comment]
@skapil Thanks for your interest in helping. Unfortunately someone is already working on this, as you can see by all the comments added above referencing commits. I believe that all of the tasks for creating tests for One and Done that currently exist have been taken, but I will look into creating some more.

**Comment by skapil** [comment]
OK. Sure, I will take when something come up next. Thanks for your response!!

**Comment by bobsilverberg** [comment]
Closed via https://github.com/mozilla/oneanddone-tests/commit/c5a7a93c48b75fef1fab7a7de8d1b45bce7dbe8a. Thanks @MonicaG!
