### ISSUE TITLE
Create a test to check the Team Detail page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/oneanddone-tests#42]
This test should be non-destructive, so it cannot log in to the site. It should do the following:
1. Open the home page.
2. Click the first task in the Suggested Tasks list.
3. Verify that the browser is on the Task Detail page for that task.
4. Click the link for the task's team.
5. Verify that the browser is on the Team Detail page for that team.
6. Verify that the task list heading is visible and includes the team's name.
7. Verify that at least one task is listed in the task listing.

**Comment by dabiid** [comment]
I've started working on this and #41

**Comment by bobsilverberg** [comment]
@dabiid That's great that you want to work on this, and I will provide whatever assistance I can. May I suggest that you work on a single issue at a time, rather than taking on both this and issue #41?

**Comment by dabiid** [comment]
Fair point :) - I started working on the other one (I just submitted the pull request) but didn't comment/figure out github right away. I just realized that this was almost the same with a few more checks on the the team detail page so it should be easy to add a new test.

**Comment by bobsilverberg** [comment]
This was completed via https://github.com/mozilla/oneanddone-tests/commit/6ec3d00fff9fc1b5026cb8c4beb715450bb5688c
