### ISSUE TITLE
Intermittent failure to click buttons in test automation

### ISSUE THREAD

**Issue by davehunt** [mozilla/oneanddone-tests#48]
Our [automated checks](https://webqa-ci.mozilla.com/view/One%20and%20Done/) are failing intermittently to click buttons in the One and Done website. [This example](https://webqa-ci.mozilla.com/view/Buildmaster/job/oneanddone.dev/781/) was an issue clicking the 'Delete Profile' button. You can see from the screenshot that the button appears to be focused but the expected page did not load.

![oneanddone](https://cloud.githubusercontent.com/assets/122800/11336156/ceec2f26-91da-11e5-814e-56d22cae8b6a.png)

I am able to replicate this issue locally. Initially I thought this might be a race condition between clicking the button and asserting that we're on the correct page, as the `wait_for_page_to_load` method doesn't actually perform a wait. I modified this locally, but was able to get this to timeout, indicating the button was not clicked. Here's my change, which might be a good idea to implement anyway:

```patch
diff --git a/pages/page.py b/pages/page.py
index 1f57039..81e03f9 100644
--- a/pages/page.py
+++ b/pages/page.py
@@ -48,7 +48,8 @@ class Page(object):
         text_fld.send_keys(text)
 
     def wait_for_page_to_load(self):
-        assert self.is_the_current_page
+        Wait(self.selenium, self.timeout, ignored_exceptions=AssertionError).until(
+            lambda s: self.is_the_current_page)
         return self

```

Suspecting recent issues with Selenium 2.48 clicking another element instead of the target one, I tried running using the latest trunk build of Selenium, which would throw an assertion in this situation. I needed to make the following modification to `base.py` for an incorrect locator, but I was still able to replicate the silent failing click:

```patch
diff --git a/pages/base.py b/pages/base.py
index a736225..638e421 100644
--- a/pages/base.py
+++ b/pages/base.py
@@ -12,7 +12,7 @@ from pages.page import Page
 
 class Base(Page):
 
-    _login_locator = (By.CSS_SELECTOR, '.browserid-login > span')
+    _login_locator = (By.CSS_SELECTOR, '.browserid-login')
     _logout_menu_item_locator = (By.CSS_SELECTOR, 'a.browserid-logout')
     _profile_link_locator = (By.ID, 'view-profile')
```

I think installed Selenium 2.47.1 and was unable to replicate the issue, suggesting that the changes in 2.48 have caused this regression. I'm not familiar enough with One and Done to know if there's a chance we're clicking too soon, but [Firediff](https://addons.mozilla.org/en-US/firefox/addon/firediff/) didn't indicate anything obvious. It could be this is a bug in Selenium, but I think we need more information or at least a simple reproducible test case before we can raise an issue there.

/cc @bobsilverberg @m8ttyB

**Comment by davehunt** [comment]
Possibly related to https://github.com/SeleniumHQ/selenium/issues/1156

**Comment by bobsilverberg** [comment]
@davehunt So if your feeling that we should just wait it out and hope for a fix? What I find confusing is that it is intermittent. I'm going to do some work on `wait_for_page_to_load` / `is_the_current_page` anyway, but you indicate that that won't eliminate the intermittent.

**Comment by davehunt** [comment]
No, I don't think we should wait it out. I was hoping that you'd have some time to look into it, as I'm not familiar with the app or framework. If it's a genuine Selenium issue then I think we could help by creating a reduced test case.

**Comment by bobsilverberg** [comment]
I have been unable to reproduce this failure locally after a couple of hundred tries. Also, I looked at CI and I only see one failure and it's just this test.

**Comment by davehunt** [comment]
Interesting, I was able to get it pretty frequently. I wonder what's different between our machines. I'll try to replicate this again today, and see if we can debug it together.

**Comment by davehunt** [comment]
I am now unable to replicate this. Let's close it for now and reopen if/when it reoccurs. We'd need it with some consistency if we have any hope of determining a fix.
